### ISSUE TITLE
Getting error in brew search

### ISSUE THREAD

**Issue by edalzell** [deligoez/homebrew-cask#1]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/6069653/108102680-b3fdc200-703d-11eb-835d-56e17d427a7b.png">

Not sure how it broke or how to fix.

**Comment by edalzell** [comment]
uninstalled all my cask apps, removed this cask and used default home-brew cask

**Comment by deligoez** [comment]
Thanks for noticing @edalzell,

It turns out that I have forked the `homebrew-cask` repository in the past.

And running `brew tap deligoez/cask` command was calling that fork.

I updated this repository and removed the fork, now everything seems to be fine.

![CleanShot 2021-02-16 at 21 53 30](https://user-images.githubusercontent.com/3030815/108108239-6a46c300-70a1-11eb-8204-473fb1ddc346.png)
